# Generated by Django 2.2.6 on 2019-10-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='quantity',
        ),
    ]
