# Generated by Django 2.2.6 on 2019-10-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_remove_topping_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
